name:                 temporal-prolog
version:              0.1.0.0
visibility:           public
id:                   temporal-prolog-0.1.0.0-inplace
key:                  temporal-prolog-0.1.0.0-inplace
maintainer:           sgschlesinger@gmail.com
author:               Samuel Schlesinger
abi:                  inplace
exposed:              True
exposed-modules:
    TemporalProlog.Interpreter TemporalProlog.Normalizer
    TemporalProlog.Parser TemporalProlog.PrettyPrint
    TemporalProlog.Syntax TemporalProlog.Unification

import-dirs:
    /Users/samuelschlesinger/projects/lang/temporal-prolog/dist-newstyle/build/aarch64-osx/ghc-9.6.7/temporal-prolog-0.1.0.0/build

library-dirs:
    /Users/samuelschlesinger/projects/lang/temporal-prolog/dist-newstyle/build/aarch64-osx/ghc-9.6.7/temporal-prolog-0.1.0.0/build

library-dirs-static:
    /Users/samuelschlesinger/projects/lang/temporal-prolog/dist-newstyle/build/aarch64-osx/ghc-9.6.7/temporal-prolog-0.1.0.0/build

dynamic-library-dirs:
    /Users/samuelschlesinger/projects/lang/temporal-prolog/dist-newstyle/build/aarch64-osx/ghc-9.6.7/temporal-prolog-0.1.0.0/build

data-dir:             /Users/samuelschlesinger/projects/lang/temporal-prolog/.
hs-libraries:         HStemporal-prolog-0.1.0.0-inplace
depends:
    base-4.18.3.0 containers-0.6.7 mgprsc-9.7.0-2e7c604a mtl-2.3.1
    text-2.0.2

haddock-interfaces:
    /Users/samuelschlesinger/projects/lang/temporal-prolog/dist-newstyle/build/aarch64-osx/ghc-9.6.7/temporal-prolog-0.1.0.0/doc/html/temporal-prolog/temporal-prolog.haddock

haddock-html:
    /Users/samuelschlesinger/projects/lang/temporal-prolog/dist-newstyle/build/aarch64-osx/ghc-9.6.7/temporal-prolog-0.1.0.0/doc/html/temporal-prolog
